version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:14.0-alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    networks:
      - app_network
    volumes:
      - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
networks:
  app_network:
